version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sojourn_db_container
    restart: always
    environment:
      POSTGRES_DB: sojourn_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"